version: "3"

services:
  postgres:
    image: postgres:15.4-alpine
    ports:
      - "5333:5432"
    volumes:
      - ~/DockerVolumes/liquibase-bug:/bitnami/postgresql
    environment:
      - POSTGRES_PASSWORD=postgres
